name: Build with Nuitka

on: [workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-22.04]
        arch: [x86, x64]
        exclude:
          - os: ubuntu-22.04
            arch: x86
    
    runs-on: ${{ matrix.os }}

    steps:
    - name: Check-out repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.8' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: ${{ matrix.arch }} # optional x64 or x86. Defaults to x64 if not specified
    
    - name: Install poetry
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry==1.8.5 virtualenv==20.34.0
    
    - name: Show versions
      run: |
        poetry --version
        poetry run python --version || true
        pipx list
        python -m pip show virtualenv

    - name: Install external dependencies (Linux)
      if: matrix.os == 'ubuntu-22.04'
      run: sudo apt install -y build-essential python3-tk

    - name: Install dependencies
      run: |
        poetry config virtualenvs.in-project true
        poetry install
        poetry run python -c "import sys; print(sys.version)"
        
    - name: Build standalone folder (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        poetry run nuitka nbstool.py

    - name: Build standalone folder (Linux)
      if: matrix.os == 'ubuntu-22.04'
      run: |
        poetry run python -m nuitka nbstool.py

    - name: Zip standalone folder
      uses: vimtor/action-zip@v1.2
      with:
        files: nbstool.dist/
        dest: NBSTool_${{ runner.os }}_${{ matrix.arch }}.zip

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ runner.os }} ${{ matrix.arch }} Build
        path: NBSTool_${{ runner.os }}_${{ matrix.arch }}.zip